-- Saturn MouseHunter 风控管理数据库表结构

-- 1. 风控规则表
CREATE TABLE md_risk_rules (
    id VARCHAR(50) PRIMARY KEY,
    rule_name VARCHAR(100) NOT NULL,
    rule_type VARCHAR(50) NOT NULL,
    description TEXT,
    rule_config JSONB DEFAULT '{}',
    threshold_value DECIMAL(20,6) NOT NULL,
    warning_threshold DECIMAL(20,6),
    scope VARCHAR(20) DEFAULT 'GLOBAL',
    target_ids TEXT[],
    trigger_conditions JSONB DEFAULT '{}',
    time_window INTEGER,
    consecutive_violations INTEGER DEFAULT 1,
    actions TEXT[],
    action_params JSONB DEFAULT '{}',
    priority INTEGER DEFAULT 5,
    is_enabled BOOLEAN DEFAULT true,
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    violation_count INTEGER DEFAULT 0,
    last_triggered_at TIMESTAMPTZ,
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 风险告警表
CREATE TABLE md_risk_alerts (
    id VARCHAR(50) PRIMARY KEY,
    rule_id VARCHAR(50) NOT NULL REFERENCES md_risk_rules(id),
    alert_level VARCHAR(20) NOT NULL,
    alert_type VARCHAR(20) NOT NULL,
    alert_message TEXT NOT NULL,
    alert_details JSONB DEFAULT '{}',
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(50) NOT NULL,
    target_name VARCHAR(200),
    current_value DECIMAL(20,6),
    threshold_value DECIMAL(20,6),
    deviation_pct DECIMAL(10,4),
    potential_loss DECIMAL(20,6),
    affected_positions INTEGER,
    risk_score DECIMAL(5,2),
    suggested_actions TEXT[],
    auto_actions_taken TEXT[],
    expires_at TIMESTAMPTZ,
    is_critical BOOLEAN DEFAULT false,
    status VARCHAR(20) DEFAULT 'OPEN',
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMPTZ,
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    generated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 风险指标表
CREATE TABLE md_risk_metrics (
    id VARCHAR(50) PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    metric_date DATE NOT NULL,
    total_exposure DECIMAL(20,6),
    net_exposure DECIMAL(20,6),
    gross_exposure DECIMAL(20,6),
    leverage_ratio DECIMAL(10,4),
    var_1d_95 DECIMAL(20,6),
    var_1d_99 DECIMAL(20,6),
    var_10d_95 DECIMAL(20,6),
    var_10d_99 DECIMAL(20,6),
    max_drawdown DECIMAL(10,4),
    current_drawdown DECIMAL(10,4),
    drawdown_duration INTEGER,
    top5_concentration DECIMAL(10,4),
    top10_concentration DECIMAL(10,4),
    herfindahl_index DECIMAL(10,4),
    avg_correlation DECIMAL(10,4),
    max_correlation DECIMAL(10,4),
    correlation_risk DECIMAL(10,4),
    liquidity_score DECIMAL(10,4),
    days_to_liquidate INTEGER,
    liquidity_risk DECIMAL(10,4),
    realized_volatility DECIMAL(10,4),
    implied_volatility DECIMAL(10,4),
    volatility_risk DECIMAL(10,4),
    beta DECIMAL(10,4),
    tracking_error DECIMAL(10,4),
    information_ratio DECIMAL(10,4),
    is_valid BOOLEAN DEFAULT true,
    quality_score DECIMAL(5,2),
    calculated_by VARCHAR(100) NOT NULL,
    calculated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(entity_type, entity_id, metric_date)
);

-- 4. 黑名单表
CREATE TABLE md_blacklist_items (
    id VARCHAR(50) PRIMARY KEY,
    list_type VARCHAR(20) NOT NULL,
    item_value VARCHAR(100) NOT NULL,
    item_name VARCHAR(200),
    category VARCHAR(50),
    tags TEXT[],
    risk_level VARCHAR(20) DEFAULT 'MEDIUM',
    risk_reason TEXT NOT NULL,
    risk_details JSONB DEFAULT '{}',
    scope VARCHAR(20) DEFAULT 'GLOBAL',
    applicable_markets TEXT[],
    applicable_strategies TEXT[],
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    requires_approval BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 5,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    is_active BOOLEAN DEFAULT true,
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    hit_count INTEGER DEFAULT 0,
    last_hit_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(list_type, item_value)
);

-- 5. 白名单表
CREATE TABLE md_whitelist_items (
    id VARCHAR(50) PRIMARY KEY,
    list_type VARCHAR(20) NOT NULL,
    item_value VARCHAR(100) NOT NULL,
    item_name VARCHAR(200),
    category VARCHAR(50),
    tags TEXT[],
    authorization_level VARCHAR(20) DEFAULT 'STANDARD',
    authorization_reason TEXT NOT NULL,
    authorization_details JSONB DEFAULT '{}',
    scope VARCHAR(20) DEFAULT 'GLOBAL',
    applicable_markets TEXT[],
    applicable_strategies TEXT[],
    usage_limits JSONB DEFAULT '{}',
    max_exposure DECIMAL(20,6),
    max_position_size DECIMAL(10,4),
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    requires_approval BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 5,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    is_active BOOLEAN DEFAULT true,
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    usage_count INTEGER DEFAULT 0,
    last_used_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(list_type, item_value)
);

-- 6. 风险场景表
CREATE TABLE md_risk_scenarios (
    id VARCHAR(50) PRIMARY KEY,
    scenario_name VARCHAR(100) NOT NULL,
    scenario_type VARCHAR(50) NOT NULL,
    description TEXT,
    scenario_params JSONB DEFAULT '{}',
    market_shocks JSONB DEFAULT '{}',
    correlation_changes JSONB DEFAULT '{}',
    stress_factors TEXT[],
    severity_level VARCHAR(20) DEFAULT 'MEDIUM',
    probability DECIMAL(5,4),
    applicable_portfolios TEXT[],
    applicable_strategies TEXT[],
    is_active BOOLEAN DEFAULT true,
    last_run_at TIMESTAMPTZ,
    run_count INTEGER DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 风险场景结果表
CREATE TABLE md_risk_scenario_results (
    id VARCHAR(50) PRIMARY KEY,
    scenario_id VARCHAR(50) NOT NULL REFERENCES md_risk_scenarios(id),
    portfolio_id VARCHAR(50) NOT NULL,
    run_date DATE NOT NULL,
    potential_loss DECIMAL(20,6) NOT NULL,
    loss_percentage DECIMAL(10,4) NOT NULL,
    worst_position_loss DECIMAL(20,6),
    positions_at_risk INTEGER DEFAULT 0,
    position_impacts JSONB DEFAULT '{}',
    sector_impacts JSONB DEFAULT '{}',
    strategy_impacts JSONB DEFAULT '{}',
    var_impact DECIMAL(20,6),
    expected_shortfall DECIMAL(20,6),
    tail_risk DECIMAL(20,6),
    is_current BOOLEAN DEFAULT true,
    calculated_by VARCHAR(100) NOT NULL,
    calculated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(scenario_id, portfolio_id, run_date)
);

-- 8. 实时风险快照表
CREATE TABLE md_realtime_risk_snapshots (
    id VARCHAR(50) PRIMARY KEY,
    snapshot_time TIMESTAMPTZ NOT NULL,
    portfolio_id VARCHAR(50) NOT NULL,
    current_var DECIMAL(20,6),
    current_exposure DECIMAL(20,6),
    current_leverage DECIMAL(10,4),
    current_drawdown DECIMAL(10,4),
    position_limit_usage DECIMAL(10,4),
    risk_limit_usage DECIMAL(10,4),
    concentration_usage DECIMAL(10,4),
    active_alerts INTEGER DEFAULT 0,
    critical_alerts INTEGER DEFAULT 0,
    overall_risk_score DECIMAL(5,2),
    risk_level VARCHAR(20) DEFAULT 'LOW',
    risk_trend VARCHAR(20),
    trend_strength DECIMAL(10,4),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. 核心指标定义表
CREATE TABLE md_core_metric_definitions (
    id VARCHAR(50) PRIMARY KEY,
    metric_name VARCHAR(100) NOT NULL,
    metric_code VARCHAR(50) NOT NULL UNIQUE,
    metric_type VARCHAR(20) NOT NULL,
    category VARCHAR(20) DEFAULT 'CORE',
    description TEXT,
    formula TEXT NOT NULL,
    unit VARCHAR(20),
    calculation_params JSONB DEFAULT '{}',
    default_period INTEGER,
    lookback_days INTEGER DEFAULT 252,
    required_fields TEXT[],
    data_sources TEXT[],
    min_data_points INTEGER DEFAULT 1,
    frequency VARCHAR(20) DEFAULT 'DAILY',
    dependencies TEXT[],
    calculation_order INTEGER DEFAULT 100,
    validation_rules JSONB DEFAULT '{}',
    valid_range_min DECIMAL(20,6),
    valid_range_max DECIMAL(20,6),
    decimal_places INTEGER DEFAULT 4,
    percentage_format BOOLEAN DEFAULT false,
    cache_enabled BOOLEAN DEFAULT true,
    cache_ttl INTEGER DEFAULT 3600,
    parallel_calculation BOOLEAN DEFAULT false,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    version VARCHAR(20) DEFAULT '1.0.0',
    is_active BOOLEAN DEFAULT true,
    usage_count INTEGER DEFAULT 0,
    last_calculated_at TIMESTAMPTZ,
    approved_by VARCHAR(100),
    approved_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. 扩展指标定义表
CREATE TABLE md_extended_metric_definitions (
    id VARCHAR(50) PRIMARY KEY,
    metric_name VARCHAR(100) NOT NULL,
    metric_code VARCHAR(50) NOT NULL UNIQUE,
    base_metrics TEXT[] NOT NULL,
    description TEXT,
    calculation_logic TEXT NOT NULL,
    formula_expression TEXT NOT NULL,
    aggregation_type VARCHAR(20) DEFAULT 'AVERAGE',
    aggregation_window INTEGER DEFAULT 20,
    smoothing_factor DECIMAL(5,4),
    combination_weights JSONB DEFAULT '{}',
    normalization_method VARCHAR(50),
    outlier_handling VARCHAR(20) DEFAULT 'IGNORE',
    condition_rules JSONB DEFAULT '[]',
    threshold_conditions JSONB DEFAULT '{}',
    time_weights JSONB,
    decay_factor DECIMAL(5,4),
    quality_checks TEXT[],
    correlation_threshold DECIMAL(5,4),
    stability_test BOOLEAN DEFAULT true,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    version VARCHAR(20) DEFAULT '1.0.0',
    is_active BOOLEAN DEFAULT true,
    complexity_score DECIMAL(5,2),
    performance_rating VARCHAR(20),
    usage_count INTEGER DEFAULT 0,
    last_calculated_at TIMESTAMPTZ,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. 指标计算任务表
CREATE TABLE md_metric_calculation_jobs (
    id VARCHAR(50) PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    metric_ids TEXT[] NOT NULL,
    target_entities TEXT[] NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    calculation_time TIME,
    calculation_params JSONB DEFAULT '{}',
    force_recalculation BOOLEAN DEFAULT false,
    incremental_mode BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 5,
    max_parallel_tasks INTEGER DEFAULT 4,
    timeout_seconds INTEGER DEFAULT 3600,
    store_intermediate BOOLEAN DEFAULT false,
    output_format VARCHAR(20) DEFAULT 'JSON',
    notification_enabled BOOLEAN DEFAULT true,
    status VARCHAR(20) DEFAULT 'PENDING',
    progress_percentage DECIMAL(5,2) DEFAULT 0,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    total_calculations INTEGER DEFAULT 0,
    successful_calculations INTEGER DEFAULT 0,
    failed_calculations INTEGER DEFAULT 0,
    skipped_calculations INTEGER DEFAULT 0,
    error_message TEXT,
    error_details JSONB,
    scheduled_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. 指标计算结果表
CREATE TABLE md_metric_calculation_results (
    id VARCHAR(50) PRIMARY KEY,
    job_id VARCHAR(50) NOT NULL REFERENCES md_metric_calculation_jobs(id),
    metric_id VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NOT NULL,
    calculation_date DATE NOT NULL,
    metric_value DECIMAL(20,6),
    raw_value DECIMAL(20,6),
    normalized_value DECIMAL(20,6),
    percentile_rank DECIMAL(5,4),
    confidence_score DECIMAL(5,4),
    data_quality_score DECIMAL(5,4),
    calculation_stability DECIMAL(5,4),
    data_points_used INTEGER DEFAULT 0,
    missing_data_points INTEGER DEFAULT 0,
    outliers_removed INTEGER DEFAULT 0,
    intermediate_values JSONB DEFAULT '{}',
    component_values JSONB DEFAULT '{}',
    calculation_method VARCHAR(100) NOT NULL,
    data_sources_used TEXT[],
    calculation_duration_ms INTEGER,
    is_valid BOOLEAN DEFAULT true,
    is_current BOOLEAN DEFAULT true,
    revision INTEGER DEFAULT 1,
    validation_passed BOOLEAN DEFAULT true,
    validation_errors TEXT[],
    validation_warnings TEXT[],
    calculated_by VARCHAR(100) NOT NULL,
    calculated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(metric_id, entity_id, calculation_date)
);

-- 创建索引
CREATE INDEX idx_risk_rules_type ON md_risk_rules(rule_type);
CREATE INDEX idx_risk_rules_enabled ON md_risk_rules(is_enabled);
CREATE INDEX idx_risk_alerts_level_status ON md_risk_alerts(alert_level, status);
CREATE INDEX idx_risk_alerts_created ON md_risk_alerts(created_at);
CREATE INDEX idx_risk_metrics_entity_date ON md_risk_metrics(entity_type, entity_id, metric_date);
CREATE INDEX idx_blacklist_items_type_value ON md_blacklist_items(list_type, item_value);
CREATE INDEX idx_whitelist_items_type_value ON md_whitelist_items(list_type, item_value);
CREATE INDEX idx_risk_scenario_results_scenario_date ON md_risk_scenario_results(scenario_id, run_date);
CREATE INDEX idx_realtime_risk_portfolio_time ON md_realtime_risk_snapshots(portfolio_id, snapshot_time);
CREATE INDEX idx_core_metrics_code ON md_core_metric_definitions(metric_code);
CREATE INDEX idx_extended_metrics_code ON md_extended_metric_definitions(metric_code);
CREATE INDEX idx_calculation_jobs_status ON md_metric_calculation_jobs(status);
CREATE INDEX idx_calculation_results_metric_entity_date ON md_metric_calculation_results(metric_id, entity_id, calculation_date);
